---
- include: play-hadoop.yml
- include: play-alladdons.yml
- name: Installing pip and mrjob
  hosts: all
  remote_user: cc
  become: yes
  tasks:
  - name: Installing pip
    easy_install: name=pip state=latest
  - name: Installing mrjob
    shell: pip install mrjob
    args:
      executable: "/bin/bash"
- name: Running a python program on front end node and fetching the results
  hosts: frontendnodes
  remote_user: hadoop
  tasks:
  - name: copying the python file to the front end node
    copy: src=MovieSimilaritiesLarge.py dest=/home/hadoop/ owner=hadoop group=hadoop mode=0777
  - name: Copying the python file for spark execution
    copy: src=Movie-Similarities-1m.py dest=/home/hadoop/ owner=hadoop group=hadoop mode=0777
  - name: Downloading the movielens 10 million ratings dataset 
    get_url: url=http://files.grouplens.org/datasets/movielens/ml-10m.zip dest=/home/hadoop/ mode=0777
  - name: Unzipping the ml-10m file
    shell: unzip ml-10m.zip
    
